baseurl = "https://example.org/"
languageCode = "en-us"
title = "goat.camp"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "goat.camp"
	description = "SEGG - Social-Ecological Graziers Guild"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "goat.camp"

		[params.navigation.links]
			about     = "About"
			services  = "Values"
			portfolio = "Projects & Services"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = ""
		subtitle   = ""
		#buttonText = "Social Ecological Graziers Guild"


	# About section
	[params.about]
		headline    = "About Us"
		header = "About Us"
		description = """Social Ecological Graziers Guild

Towards the protection, education, and proliferation of native wildland ecosystems; integrated community food and medicine; environmental regeneration praxis, and social ecology

Social Ecology-
noun
1 advocates a reconstructive and transformative outlook on social and environmental issues, and promotes a directly democratic, confederal politics. Social Ecology envisions a moral economy that moves beyond scarcity and hierarchy, toward a world that reharmonizes human communities with the natural world, while celebrating diversity, creativity and freedom.

Guild -
noun
1 an organization of persons with related interests, goals, etc., especially one formed for mutual aid or protection.

Areas of Social Ecology:
    • Social theory
    • Ecological and social activism
    • Ecological land use and organic agriculture
    • Ecofeminism and other ecophilosophies
    • Science and technology studies
    • Globalization and global justice
    • Community organizing and development
    • Food systems and agricultural policy
    • Ecological alternatives in education
    • Environmental issues and politics
    • Environmental justice and community health
    • Economic relocalization
    • Media democracy """
		#buttonText  = "Get started!"

	# Service section
	[params.services]
		headline = "Our Values"

        [[params.services.list]]
	    			icon = "fa-campground"
						#icon = "fa-campground"
						title = "Diversity"
            description = "Our templates are updated regularly so they don't break."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Creativity"
			description = "You can use this theme as is, or you can make changes!"

		[[params.services.list]]
            icon = "fa-newspaper"
            title = "Freedom"
            description = "We update dependencies to keep things fresh."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Community"
            description = "Interdependence and stuff"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Learn More!"

		[params.aside.button]
			text = "Link to something"
			link = "broken link"

	# Contact section
	[params.contact]
		headline = "Contact Us!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "585.705.8063"
		email = "segg@tuta.io"

	# Google Maps section
        #[params.location]
	 #	latitude  = "34.007850"
	 #	longitude = "-118.499305"
	 #	maps_api_key = ""
